name: Generate Plots from Data
on:
  # Allow manual runs from the Actions tab
  workflow_dispatch:

# Grant the action permission to push commits back to this repo
permissions:
  contents: write

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # Specify the R version you want
          r-version: '4.3' 
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
      - name: Run R script
        run: |
          # This executes your script
          Rscript generateBarPlot.r
          Rscript generateBarPlot2.r
      - name: Commit and Push output file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output_data.txt
          # Check if the file has changed before committing
          if ! git diff --quiet --cached; then
            git commit -m "Chore: Auto-update output_data.txt"
            git push
          else
            echo "No changes to commit."
          fi
